### PR TITLE
Extend fallback configuration to read all OAuth2 options

### PR DESCRIPTION
**Pull request by jcdelepine**
## Problem

The fallback configuration file (`/etc/sasl2/oauth2.conf`) only read 4 basic options:
- `oauth2_discovery_url`
- `oauth2_issuer`
- `oauth2_client_id`
- `oauth2_audience`

This caused authentication failures with Postfix SMTP:
```
warning: SASL authentication failure: oauth2_plugin: User claim 'email' not found or not a string in JWT
```
even with "oauth2_user_claim: sub" put in /etc/sasl2/smtpd.conf, /etc/postfix/sasl/smtpd.conf and /etc/sasl2/oauth2.conf
 
## Root Cause

Postfix's SASL implementation doesn't transmit plugin-specific options via SASL `getopt()`. 
From the [Postfix SASL README](https://www.postfix.org/SASL_README.html):

> "This means that some SASL-related configuration files will belong to Postfix, 
> while other configuration files belong to the specific SASL implementation that Postfix will use."

The fallback configuration mechanism was designed for this scenario but was incomplete.

## Solution

Extended `oauth2_load_fallback_config()` to read **all** OAuth2 configuration options:
- All singular options: `oauth2_user_claim`, `oauth2_client_secret`, `oauth2_scope`, etc.
- Plural forms: `oauth2_discovery_urls`, `oauth2_issuers`, `oauth2_audiences`
- Boolean/integer options: `oauth2_debug`, `oauth2_timeout`, `oauth2_verify_signature`, etc.

### Modified Files

1. **`oauth2_plugin.h`**
   - Added allocation tracking fields to `oauth2_config_t` for proper memory management

2. **`oauth2_config.c`**
   - Extended `oauth2_load_fallback_config()` to read all options
   - Modified `oauth2_config_load()` to not override fallback values
   - Modified `oauth2_config_free()` to free fallback-allocated strings
   - Modified `oauth2_config_init()` to initialize sentinel values

3. **`README.md`**
   - Clarified fallback configuration usage
   - Updated Postfix integration section with correct configuration
   - Referenced official Postfix documentation

## Testing

Tested with Postfix SMTP server using `/etc/sasl2/oauth2.conf`:
```ini
oauth2_discovery_url: https://cas.server.fr/oidc/.well-known/openid-configuration
oauth2_client_id: my_client
oauth2_user_claim: sub
oauth2_debug: yes
```

Result:  Authentication successful

## Compatibility

-  Cyrus IMAP: Continues to work (uses SASL getopt())
-  Postfix SMTP: Now works (uses fallback file)
-  Backward compatible with existing configurations

## References

- Postfix SASL README: https://www.postfix.org/SASL_README.html

### CODE REVIEW

**Comment by stefb69** [comment]
Hello, thanks for that, i'll review it, and include it very soon.

**Comment by stefb69** [comment]
It doesn't compile... (not compatible with the all versions of liboauth2) and automated build fails. The fix should build on all targets. Check the build logs please.


```
#15 6.724 + /usr/bin/make -O -j4 V=1 VERBOSE=1
#15 6.729 /usr/bin/make  all-am
#15 6.830 oauth2_server.c: In function 'oauth2_validate_jwt_token':
#15 6.830 oauth2_server.c:252:34: error: too few arguments to function 'oauth2_token_verify'; expected 6, have 5
#15 6.830   252 |             validation_success = oauth2_token_verify(config->oauth2_log, NULL, verify, token, &json_payload);
#15 6.830       |                                  ^~~~~~~~~~~~~~~~~~~
#15 6.830 In file included from oauth2_plugin.h:22,
#15 6.830                  from oauth2_server.c:6:
#15 6.830 /usr/include/oauth2/oauth2.h:79:6: note: declared here
#15 6.830    79 | bool oauth2_token_verify(oauth2_log_t *log, oauth2_http_request_t *request,
#15 6.830       |      ^~~~~~~~~~~~~~~~~~~
#15 6.830 make[1]: *** [Makefile:785: liboauth2_la-oauth2_server.lo] Error 1
#15 6.830 make[1]: Entering directory '/root/rpmbuild/BUILD/cyrus-sasl-oauth2-oidc-1.0.0-build/cyrus-sasl-oauth2-oidc-1.0.0'
```

**Comment by jcdelepine** [comment]
Hi,

You're absolutely right - the compilation failure is due to a liboauth2 API change in version 2.2.0.

I've just submitted PR #2 (Fix compatibility with liboauth2 >= 2.2.0) which proposes a resolution to this issue.

**The compilation error is not caused by PR #5 ** (fallback configuration) - it was a pre-existing bug in the codebase that prevented compilation on systems with liboauth2 >= 2.2.0 (Debian Unstable, Fedora 41+, GitHub CI).

**Suggested merge order:**
1. Merge PR #6 first (fixes compilation on all liboauth2 versions)
2. Then merge PR #5 (extends fallback configuration)

Both PRs are independent and can be reviewed separately, but PR #6 should be merged first to restore compilation on all platforms.

Thanks for reviewing!

**Comment by stefb69** [comment]
Superseded by #8 which reimplements the same functionality with bug fixes (memory leaks, inconsistent override behavior, secure secret clearing).
